// Code generated by "stringer -linecomment -type NotificationState -output notification_state_string.go"; DO NOT EDIT.

package incident

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotificationStateNull-0]
	_ = x[NotificationStateSuppressed-1]
	_ = x[NotificationStatePending-2]
	_ = x[NotificationStateSent-3]
	_ = x[NotificationStateFailed-4]
	_ = x[notificationStateMax-5]
}

const _NotificationState_name = "NotificationStateNullsuppressedpendingsentfailedinternal"

var _NotificationState_index = [...]uint8{0, 21, 31, 38, 42, 48, 56}

func (i NotificationState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NotificationState_index)-1 {
		return "NotificationState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotificationState_name[_NotificationState_index[idx]:_NotificationState_index[idx+1]]
}
