//go:generate go tool stringer -type EnvelopeFmt -linecomment -output envelope_string.go

package event

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/icinga/icinga-go-library/types"
)

// EnvelopeFmt describes the format of the payload stored in the event queue.
type EnvelopeFmt uint8

const (
	EnvelopeFmtNone EnvelopeFmt = iota // none

	// EnvelopeFmtEvent indicates that the payload is a JSON representation of an event.Event.
	EnvelopeFmtEvent // event

	envelopeFmtMax // internal
)

const (
	// EnvelopeEventVersion defines the version of the event envelope format supported by this node.
	//
	// It is used to ensure compatibility between different versions of the event queue and the event processing logic.
	// Nodes with newer envelope versions are guaranteed to be compatible with older versions, but nodes with older
	// envelope versions may not be able to process events from newer versions.
	EnvelopeEventVersion = 1
)

// Envelope stores metadata about the payload it embodies, such as its version and format.
type Envelope struct {
	Version uint8       `json:"version"`
	Format  EnvelopeFmt `json:"format"`
	// Time represents the time when this envelope was generated and enqueued into the job queue.
	//
	// It is not part of the Payload so that the SHA256 hash used for deduplication is not affected by the time
	// the event was enqueued. For instance, for every event enqueued by the listener, Time represents the time
	// when the listener received the event, not when the event was generated by the source. So, if the same event
	// is enqueued multiple times, Time will be different, but the SHA256 hash will be the same, allowing the
	// deduplication logic to work correctly.
	Time    types.UnixMilli `json:"time,omitzero"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

// Scan implements the [sql.Scanner] interface for Envelope.
func (e *Envelope) Scan(src any) error {
	if src == nil {
		return nil
	}

	switch val := src.(type) {
	case string:
		return json.Unmarshal([]byte(val), e)
	case []byte:
		return json.Unmarshal(val, e)
	default:
		return fmt.Errorf("cannot scan envelope from %T", src)
	}
}

// Value implements the [driver.Valuer] interface for Envelope.
func (e Envelope) Value() (driver.Value, error) { return json.Marshal(e) }

// MarshalJSON implements the json.Marshaler interface.
func (f EnvelopeFmt) MarshalJSON() ([]byte, error) {
	return []byte(`"` + f.String() + `"`), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (f *EnvelopeFmt) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	for envfmt := range envelopeFmtMax {
		if envfmt != EnvelopeFmtNone && s == envfmt.String() {
			*f = envfmt
			return nil
		}
	}
	return fmt.Errorf("unknown envelope format %q", s)
}
