// Code generated by "stringer -type EnvelopeFmt -linecomment -output envelope_string.go"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnvelopeFmtNone-0]
	_ = x[EnvelopeFmtEvent-1]
	_ = x[envelopeFmtMax-2]
}

const _EnvelopeFmt_name = "noneeventinternal"

var _EnvelopeFmt_index = [...]uint8{0, 4, 9, 17}

func (i EnvelopeFmt) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EnvelopeFmt_index)-1 {
		return "EnvelopeFmt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnvelopeFmt_name[_EnvelopeFmt_index[idx]:_EnvelopeFmt_index[idx+1]]
}
