// Code generated by "stringer -type Action -linecomment -output quick_action_string.go"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionInvalid-0]
	_ = x[ActionManage-1]
	_ = x[ActionUnmanage-2]
	_ = x[ActionSubscribe-3]
	_ = x[ActionUnsubscribe-4]
	_ = x[actionMax-5]
}

const _Action_name = "invalidmanageunmanagesubscribeunsubscribeinternal"

var _Action_index = [...]uint8{0, 7, 13, 21, 30, 41, 49}

func (i Action) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Action_index)-1 {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[idx]:_Action_index[idx+1]]
}
