// Code generated by "stringer -type=State -linecomment -output=state_string.go"; DO NOT EDIT.

package notification

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateNull-0]
	_ = x[StateSuppressed-1]
	_ = x[StatePending-2]
	_ = x[StateSent-3]
	_ = x[StateFailed-4]
	_ = x[_stateMax-5]
}

const _State_name = "nullsuppressedpendingsentfailedinternal"

var _State_index = [...]uint8{0, 4, 14, 21, 25, 31, 39}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
