package object

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"

	"github.com/icinga/icinga-go-library/database"
	"github.com/icinga/icinga-go-library/types"
	baseUtils "github.com/icinga/icinga-go-library/utils"
	"github.com/icinga/icinga-notifications/internal/event"
	"github.com/icinga/icinga-notifications/internal/utils"
	"github.com/jmoiron/sqlx"
)

type Object struct {
	ID   types.Binary `db:"id"`
	Name string       `db:"name"`
	URL  types.String `db:"url"`

	Tags map[string]string `db:"-"`
}

// New creates a new object from the given event.
func New(ev *event.Event) *Object {
	return &Object{
		ID:   ID(ev.Tags),
		Name: ev.Name,
		URL:  types.MakeString(ev.URL, types.TransformEmptyStringToNull),
		Tags: ev.Tags,
	}
}

// Get the Object for the requested ID from the database.
func Get(ctx context.Context, db *database.DB, id types.Binary) (*Object, error) {
	o := new(Object)
	stmt := db.Rebind(db.BuildSelectStmt(o, o) + ` WHERE "id" = ?`)
	err := db.GetContext(ctx, o, stmt, id)
	if err != nil {
		return nil, fmt.Errorf("cannot get object %q from database: %w", id, err)
	}

	o.Tags = make(map[string]string)
	err = utils.ForEachRow(ctx, db, db, "object_id", []types.Binary{id}, func(ir *IdTagRow) {
		o.Tags[ir.Tag] = ir.Value
	})
	if err != nil {
		return nil, fmt.Errorf("cannot fetch object id tags from database: %w", err)
	}

	return o, nil
}

// SyncFromEvent syncs the object in the database with the given event.
//
// It inserts or updates the object and its tags in the database based on the provided event.
// The function uses the specified tx to ensure that both the object and its tags are updated atomically.
//
// Returns error on any database failure, otherwise returns the updated object.
func SyncFromEvent(ctx context.Context, db *database.DB, tx *sqlx.Tx, ev *event.Event) (*Object, error) {
	o := New(ev)
	stmt, _ := db.BuildUpsertStmt(o)
	if _, err := tx.NamedExecContext(ctx, stmt, o); err != nil {
		return nil, fmt.Errorf("failed to insert object: %w", err)
	}

	stmt, _ = db.BuildUpsertStmt(new(IdTagRow))
	if _, err := tx.NamedExecContext(ctx, stmt, mapToIdTagRows(o.ID, ev.Tags)); err != nil {
		return nil, fmt.Errorf("failed to upsert object id tags: %w", err)
	}

	sa := &Source{ObjectID: o.ID, SourceID: ev.SourceId}
	stmt, _ = db.BuildUpsertStmt(sa)
	if _, err := tx.NamedExecContext(ctx, stmt, sa); err != nil {
		return nil, fmt.Errorf("failed to upsert object source association: %w", err)
	}

	return o, nil
}

func (o *Object) DisplayName() string {
	if o.Name != "" {
		return o.Name
	}

	j, err := json.Marshal(o.Tags)
	if err != nil {
		panic(err)
	}
	return string(j)
}

// ID generates a stable identifier based on the given ID tags.
//
// The identifier is generated by creating a SHA256 hash of the concatenated key-value pairs of the tags,
// sorted by key to ensure consistent ordering. The resulting hash is returned as a [types.Binary] value.
//
// The implementation of this function must remain stable to not break existing object references in the database.
// Any changes to the algorithm must be carefully considered and documented, as they may affect the integrity of
// existing data.
func ID(tags map[string]string) types.Binary {
	h := sha256.New()
	for k, v := range baseUtils.IterateOrderedMap(tags) {
		h.Write([]byte(k))
		h.Write([]byte{0})
		h.Write([]byte(v))
		h.Write([]byte{0})
	}

	return h.Sum(nil)
}

// mapToIdTagRows transforms the object tags map to a slice of TagRow struct.
func mapToIdTagRows(objectId types.Binary, tags map[string]string) []*IdTagRow {
	var tagRows []*IdTagRow
	for key, val := range tags {
		tagRows = append(tagRows, &IdTagRow{
			ObjectId: objectId,
			Tag:      key,
			Value:    val,
		})
	}

	return tagRows
}
