// Code generated by "stringer -linecomment -type Type -output rule_type_string.go"; DO NOT EDIT.

package rule

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeEscalation-0]
	_ = x[TypeRouting-1]
	_ = x[_typeMax-2]
}

const _Type_name = "escalationroutinginternal"

var _Type_index = [...]uint8{0, 10, 17, 25}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
