name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -v ./...
    - name: Vet
      run: go vet ./...
