name: Go

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -v ./...
    - name: Vet
      run: go vet ./...
