name: Go

on:
  push:
    branches: [ main ]
  pull_request: {}

permissions:
  # https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
  contents: read

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -v ./...
    - name: Vet
      run: go vet ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest
        # Enable the gosec linter w/o having to create a .golangci.yml config
        args: -E gosec
        skip-cache: true
