name: Tests with database

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  ICINGA_NOTIFICATIONS_ICINGAWEB2_URL: https://localhost/icingaweb2
  ICINGA_NOTIFICATIONS_CHANNELS_DIR: ${{ github.workspace }}/channels
  ICINGA_NOTIFICATIONS_DATABASE_DATABASE: notifications
  ICINGA_NOTIFICATIONS_DATABASE_PASSWORD: notifications
  ICINGA_NOTIFICATIONS_DATABASE_HOST: 127.0.0.1

jobs:
  mysql:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - mysql:5.7
          - mysql:8.0
          - mysql:8
          - mysql:latest
          - mariadb:10.5
          - mariadb:10.6
          - mariadb:10
          - mariadb:11.0
          - mariadb:11.1
          - mariadb:11.2
          - mariadb:latest

    env:
      ICINGA_NOTIFICATIONS_DATABASE_TYPE: mysql
      ICINGA_NOTIFICATIONS_DATABASE_USER: root
      ICINGA_NOTIFICATIONS_DATABASE_PORT: 3306

    services:
      mysql:
        image: ${{ matrix.image }}
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.ICINGA_NOTIFICATIONS_DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ env.ICINGA_NOTIFICATIONS_DATABASE_DATABASE }}
        # Wait until MySQL becomes ready
        options: >-
          --health-cmd "${{ (startsWith(matrix.image, 'mysql:') || startsWith(matrix.image, 'mariadb:10')) && 'mysqladmin ping' || 'healthcheck.sh --connect --innodb_initialized' }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 3306:3306

    steps:
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Importing Schema
        run: >
          mysql -h127.0.0.1 -u$ICINGA_NOTIFICATIONS_DATABASE_USER -p$ICINGA_NOTIFICATIONS_DATABASE_PASSWORD
          $ICINGA_NOTIFICATIONS_DATABASE_DATABASE < ${{ github.workspace }}/schema/mysql/schema.sql

      - name: Download dependencies
        run: go get -v -t -d ./...

      - name: Build Channels
        run: |
          mkdir -p ${{ github.workspace }}/channels
          go build -o ${{ github.workspace }}/channels './cmd/channels/...'

      - name: Run tests
        timeout-minutes: 10
        run: go test -v -timeout 5m ./...

  postgresql:
    name: PostgreSQL ${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["9.6", "10", "11", "12", "13", "14", "15", "latest"]

    env:
      ICINGA_NOTIFICATIONS_DATABASE_TYPE: pgsql
      ICINGA_NOTIFICATIONS_DATABASE_USER: postgres
      ICINGA_NOTIFICATIONS_DATABASE_PORT: 5432

    services:
      postgres:
        image: postgres:${{ matrix.version }}
        env:
          POSTGRES_PASSWORD: ${{ env.ICINGA_NOTIFICATIONS_DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.ICINGA_NOTIFICATIONS_DATABASE_DATABASE }}
        # Wait until postgres becomes ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Importing Schema
        env:
          PGPASSWORD: ${{ env.ICINGA_NOTIFICATIONS_DATABASE_PASSWORD }}
        run: |
          psql -U postgres -w -h 127.0.0.1 -d ${{ env.ICINGA_NOTIFICATIONS_DATABASE_DATABASE }} < ${{ github.workspace }}/schema/pgsql/schema.sql

      - name: Download dependencies
        run: go get -v -t -d ./...

      - name: Build Channels
        run: |
          mkdir -p ${{ github.workspace }}/channels
          go build -o ${{ github.workspace }}/channels './cmd/channels/...'

      - name: Run tests
        timeout-minutes: 10
        run: go test -v -timeout 5m ./...
